uploads = []
generated = []

[[outputs]]
id = "AstEsYiWIFWg89rlqYOxJ"
uri = "file://experiment7_mlflow_lab_record.txt"
type = "text"
title = "Experiment 7 – MLFlow Lab Record"

[[outputs]]
id = "BW__tqdm2xBO6NQVDGQxX"
uri = "file://assignment_8.txt"
type = "text"
title = "Experiment 8 – Optuna Hyperparameter Tuning Lab Record"
