# Generated by Django 5.2.10 on 2026-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='ai_estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='ai_suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
