# Generated by Django 5.2.10 on 2026-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_ai_category_habit_ai_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='widget_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
