# Generated by Django 5.2.10 on 2026-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_widget_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitresponse',
            name='feedback_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
