# Generated by Django 5.2.10 on 2026-02-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habitresponse_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(default=28),
        ),
    ]
