# Generated by Django 5.2.10 on 2026-02-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='minutes_after',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='habit',
            name='minutes_before',
            field=models.IntegerField(default=5),
        ),
    ]
