# Generated by Django 5.2.10 on 2026-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_airecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='recurrence',
            field=models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='selected_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
